name: flutter_vnd_keyboard
description: Vietnamese đồng keyboard for Flutter.
version: 0.0.1
homepage: https://github.com/daohoangson/flutter-vnd_keyboard

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  lint: ^2.0.1
  mocktail: ^0.3.0

flutter:
  assets:
    # needed to trigger the FontManifest.json to be included
    - images/
  uses-material-design: true
