name: Example
on:
  push:

jobs:
  apk:
    name: Build Android APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - run: flutter build apk --split-per-abi
        working-directory: example
      - uses: actions/upload-artifact@v3
        with:
          name: armeabi-v7a.apk
          path: example/build/app/outputs/apk/release/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: arm64-v8a.apk
          path: example/build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64.apk
          path: example/build/app/outputs/apk/release/app-x86_64-release.apk
